# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AirQuality' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AirQuality
  pod 'Charts'
  pod 'Starscream'
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'AirQualityTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxNimble'
  end

  target 'AirQualityUITests' do
    # Pods for testing
  end

end
